### ISSUE TITLE
Game not detecting .NET 4.8

### ISSUE THREAD

**Issue by pastelkiwi772** [tivtag/Zelda#1]
my laptop already has version 4.8 downloaded yet the game doesn't recognize that and it keeps sending me error messages and won't run. I've tried multiple times. Please help if you can.

**Comment by pastelkiwi772** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/69669442/90225900-01ffe780-ddc7-11ea-8af4-34a674141487.png)


this is the error in plain text below:


System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Xna.Framework.Graphics.dll' or one of its dependencies. The specified module could not be found.
File name: 'Microsoft.Xna.Framework.Graphics.dll'
   at Zelda.Graphics.GameGraphics..ctor(ZeldaGame game)
   at Zelda.ZeldaGame..ctor()
   at Zelda.Program.Run()
   at Zelda.Program.Main()

**Comment by tivtag** [comment]
Hi @pastelkiwi772!

Please first try updating your DirectX runtime: https://www.microsoft.com/en-us/download/details.aspx?id=35

If this doesn't work you could try to install the Microsoft XNA Framework Redistributable 4.0: https://www.microsoft.com/en-us/download/details.aspx?id=20914

Installing the XNA Redistributable shouldn't be required, but it does also update some other DirectX drivers.

Please report back!
Enjoy :-)
- Paul

P.S.: Be sure to play with the latest patch! :-D

**Comment by pastelkiwi772** [comment]
updating DirectX runtime fixed the problem thanks

**Comment by tivtag** [comment]
Updating DirectX runtime (https://www.microsoft.com/en-us/download/details.aspx?id=35) helped -> closing
