### ISSUE TITLE
Credits for graphics

### ISSUE THREAD

**Issue by mileswest07** [tivtag/Zelda#2]
Noticing that [items sheet](https://github.com/tivtag/Zelda/blob/master/Content/BlackCrown_ContentProject/Content/Textures/Items.png) has a variety of graphic styles, some custom-made and some official licensed assets. Will proper credit be given to each of those original authors at some point?

**Comment by tivtag** [comment]
Hi Chaos! There is in the credits file! If you know of anything missing,
feel free to write. :)

**Comment by mileswest07** [comment]
Yes actually, there are some missing.

Namely, [me](https://www.spriters-resource.com/custom_edited/thelegendofzeldacustoms/sheet/60633/).

Please do the due diligence to credit the sprite creators, otherwise it looks like theft.
Thank you.

**Comment by tivtag** [comment]
Hi Chaos!

I will add you asap :-) thanks for your great work! I couldn’t have created
the game without people like you!

If you know anyone else, that I should add please let me know.

I am planning to also create an ingame credits screen.

Cheers

**Comment by tivtag** [comment]
See commit: https://github.com/tivtag/Zelda/commit/b85d47c7d9ab9fac6c9d264fd496898a6f09e81d
